import { PageShell } from "@/components/PageShell";

export default function Page() {
  return (
    <PageShell lang="en" title="Privacy Policy">
      <p className="mt-4 text-muted">,Privacy Policy</p>
      <p className="mt-4 text-muted">Effective Date: 07/11/2019</p>
      <p className="mt-4 text-muted">Applicable To The Following Website:</p>
      <p className="mt-4 text-muted">https://www.tuataras.net</p>
      <p className="mt-4 text-muted">Article 1 - DEFINITIONS:</p>
      <p className="mt-4 text-muted">a) APPLICABLE WEBSITE: This Privacy Policy will refer to and be applicable to the Website listed above, which shall hereinafter be referred to as "Website." Any listed Website may also refer to a corresponding mobile application, should one be currently in use or hereinafter developed.</p>
      <p className="mt-4 text-muted">b) EFFECTIVE DATE: "Effective Date" means the date this Privacy Policy comes into force and effect.</p>
      <p className="mt-4 text-muted">c) PARTIES: The parties to this privacy policy are the following data controller: TUATARAS LLC. ("Data Controller") and you, as the user of this Website. Hereinafter, the parties will individually be referred to as "Party" and collectively as "Parties."</p>
      <p className="mt-4 text-muted">d) DATA CONTROLLER: Data Controller is the publisher, owner, and operator of the Website and is the Party responsible for the collection of information described herein. Data Controller shall be referred to either by Data Controller's name or "Data Controller," as listed above. If Data Controller or Data Controller's property shall be referred to through first-person pronouns, it shall be through the use of the following: us, we, our, ours, etc.</p>
      <p className="mt-4 text-muted">e) YOU: Should you agree to this Privacy Policy and continue your use of the Website, you will be referred to herein as either you, the user, or if any second-person pronouns are required and applicable, such pronouns as 'your", "yours", etc.</p>
      <p className="mt-4 text-muted">f) SERVICES: "Services" means any services that we make available for sale on the Website.</p>
      <p className="mt-4 text-muted">g) PERSONAL DATA: "Personal DATA" means personal data and information that we obtain from you in connection with your use of the Website which is capable of identifying you in any manner.</p>
      <p className="mt-4 text-muted">Article 2 - GENERAL INFORMATION:</p>
      <p className="mt-4 text-muted">This privacy policy (hereinafter "Privacy Policy") describes how we collect and use the Personal Data that we receive about you, as well as your rights in relation to that Personal Data, when you visit our Website or use our Services.</p>
      <p className="mt-4 text-muted">This Privacy Policy does not cover any information that we may receive about you through sources other than the use of our Website. The Website may link out to other websites or mobile applications, but this Privacy Policy does not and will not apply to any of those linked websites or applications.</p>
      <p className="mt-4 text-muted">We are committed to the protection of your privacy while you use our Website.</p>
      <p className="mt-4 text-muted">By continuing to use our Website, you acknowledge that you have had the chance to review and consider this Privacy Policy, and you acknowledge that you agree to it. This means that you also consent to the use of your information and the method of disclosure as described in this Privacy Policy. If you do not understand the Privacy Policy or do not agree to it then you agree to immediately cease your use of our Website.</p>
      <p className="mt-4 text-muted">Article 3 - CONTACT:</p>
      <p className="mt-4 text-muted">The Party responsible for the processing of your personal data is as follows: TUATARAS LLC. The Data Controller may be contacted as follows:</p>
      <p className="mt-4 text-muted">E-Mail: info@tuataras.local</p>
      <p className="mt-4 text-muted">The Data Controller and operator of the Website are one and the same.</p>
      <p className="mt-4 text-muted">Article 4 - LOCATION:</p>
      <p className="mt-4 text-muted">Please be advised the data processing activities take place in the United States, outside the European Economic Area. Data may also be transferred to companies within the United States, but will only be done so in a manner that complies with the EU's General Data Protection Regulation or GDPR. The location where the data processing activities take place is as follows:</p>
      <p className="mt-4 text-muted">California, United States</p>
      <p className="mt-4 text-muted">Caracas, Venezuela</p>
      <p className="mt-4 text-muted">Article 5 - MODIFICATIONS AND REVISIONS:</p>
      <p className="mt-4 text-muted">We reserve the right to modify, revise, or otherwise amend this Privacy Policy at any time and in any manner. If we do so, however, we will notify you and obtain your consent to the change in processing. Unless we specifically obtain your consent, any changes to the Privacy Policy will only impact the information collected on or after the date of the change. It is also your responsibility to periodically check this page for any such modification, revision or amendment.</p>
      <p className="mt-4 text-muted">Article 6 - THE PERSONAL DATA WE RECEIVE FROM YOU:</p>
      <p className="mt-4 text-muted">Depending on how you use our Website, you will be subject to different types of Personal Data collected and different manners of collection:</p>
      <p className="mt-4 text-muted">a) Registered users: You, as a user of the Website, may be asked to register in order to use the Website or to purchase the Services available for sale.</p>
      <p className="mt-4 text-muted">During the process of your registration, we will collect some of the following Personal Data from you through your voluntary disclosure:</p>
      <p className="mt-4 text-muted">Name, E-Mail</p>
      <p className="mt-4 text-muted">Personal Data may be asked for in relation to:</p>
      <p className="mt-4 text-muted">I) Interaction with our representatives in any way</p>
      <p className="mt-4 text-muted">II) making purchases</p>
      <p className="mt-4 text-muted">III) receiving notifications by text message or email about marketing</p>
      <p className="mt-4 text-muted">IV) receiving general emails from us</p>
      <p className="mt-4 text-muted">V) commenting on our content or other user-generated content on our Website, such as blogs, articles, photographs or videos, or participating in our forums, bulletin boards, chat rooms or other similar features</p>
      <p className="mt-4 text-muted">By undergoing the registration process, you consent to us collecting your Personal Data, including the Personal Data described in this clause, as well as storing, using or disclosing your Personal Data in accordance with this Privacy Policy.</p>
      <p className="mt-4 text-muted">b) Unregistered users: If you are a passive user of the Website and do not register for any purchases or other service, you may still be subject to certain passive data collection ("Passive Data Collection"). Such Passive Data Collection may include through cookies, as described below, IP address information, location information, and certain browser data, such as history and/or session information.</p>
      <p className="mt-4 text-muted">c) All users: The Passive Data Collection which applies to Unregistered users shall also apply to all other users and/or visitors of our Website.</p>
      <p className="mt-4 text-muted">d) Sales &amp; Billing Information: In order to purchase any of the services on the Website, you will be asked to provide certain credit information, billing address information, and possibly additional specific information so that you may be properly charged for your purchases. This payment and billing information will not be stored and will be used exclusively to assist with your one-time purchase.</p>
      <p className="mt-4 text-muted">e) Email Marketing: You may be asked to provide certain Personal Data, such as your name and email address, for the purpose of receiving email marketing communications. This information will only be obtained through your voluntary disclosure and you will be asked to affirmatively opt-in to email marketing communications.</p>
      <p className="mt-4 text-muted">f) Content Interaction: Our Website may allow you to comment on the content that we provide or the content that other users provide, such as blogs, multimedia, or forum posts. If so, we may collect some Personal Data from you at that time, such as, but not limited to, username or email address.</p>
      <p className="mt-4 text-muted">g) Combined or Aggregated Information: We may combine or aggregate some of your Personal Data in order to better serve you and to better enhance and update our Website for your and other consumers' use.</p>
      <p className="mt-4 text-muted">We may also share such aggregated information with others, but only if that aggregated information does not contain any Personal Data.</p>
      <p className="mt-4 text-muted">Article 7 - THE PERSONAL DATA WE RECEIVE AUTOMATICALLY:</p>
      <p className="mt-4 text-muted">Cookies: We may collect information from you through automatic tracking systems (such as information about your browsing preferences) as well as through information that you volunteer to us (such as information that you provide during a registration process or at other times while using the Website, as described above).</p>
      <p className="mt-4 text-muted">For example, we use cookies to make your browsing experience easier and more intuitive: cookies are small strings of text used to store some information that may concern the user, his or her preferences or the device they are using to access the Internet (such as a computer, tablet, or mobile phone). Cookies are mainly used to adapt the operation of the site to your expectations, offering a more personalized browsing experience and memorizing the choices you made previously.</p>
      <p className="mt-4 text-muted">A cookie consists of a reduced set of data transferred to your browser from a web server and it can only be read by the server that made the transfer. This is not executable code and does not transmit viruses.</p>
      <p className="mt-4 text-muted">Cookies do not record or store any Personal Data. If you want, you can prevent the use of cookies, but then you may not be able to use our Website as we intend. To proceed without changing the options related to cookies, simply continue to use our Website.</p>
      <p className="mt-4 text-muted">Technical cookies: Technical cookies, which can also sometimes be called HTML cookies, are used for navigation and to facilitate your access to and use of the site. They are necessary for the transmission of communications on the network or to supply services requested by you. The use of technical cookies allows the safe and efficient use of the site.</p>
      <p className="mt-4 text-muted">You can manage or request the general deactivation or cancelation of cookies through your browser. If you do this though, please be advised this action might slow down or prevent access to some parts of the site.</p>
      <p className="mt-4 text-muted">Cookies may also be retransmitted by an analytics or statistics provider to collect aggregated information on the number of users and how they visit the Website. These are also considered technical cookies when they operate as described.</p>
      <p className="mt-4 text-muted">Temporary session cookies are deleted automatically at the end of the browsing session - these are mostly used to identify you and ensure that you don't have to log in each time - whereas permanent cookies remain active longer than just one particular session.</p>
      <p className="mt-4 text-muted">Third-party cookies: We may also utilize third-party cookies, which are cookies sent by a third-party to your computer. Permanent cookies are often third-party cookies. The majority of third-party cookies consist of tracking cookies used to identify online behavior, understand interests and then customize advertising for users.</p>
      <p className="mt-4 text-muted">Third-party analytical cookies may also be installed. They are sent from the domains of the aforementioned third parties external to the site. Third-party analytical cookies are used to detect information on user behavior on our Website. This place anonymously, in order to monitor the performance and improve the usability of the site. Third-party profiling cookies are used to create profiles relating to users, in order to propose advertising in line with the choices expressed by the users themselves.</p>
      <p className="mt-4 text-muted">Profiling cookies: We may also use profiling cookies, which are those that create profiles related to the user and are used in order to send advertising to the user's browser.</p>
      <p className="mt-4 text-muted">When these types of cookies are used, we will receive your explicit consent.</p>
      <p className="mt-4 text-muted">Support in configuring your browser: You can manage cookie through the settings of your browser on your device. However, deleting cookies from your browser may remove the preferences you have set for this Website.</p>
      <p className="mt-4 text-muted">For further information and support, you can also visit the specific help page of the web browser you are using:</p>
      <p className="mt-4 text-muted">- Internet Explorer: http://windows.microsoft.com/en-us/windows-vista/block-or-allow-cookies</p>
      <p className="mt-4 text-muted">- Firefox: https://support.mozilla.org/en-us/kb/enable-and-disable-cookies-website-preferences</p>
      <p className="mt-4 text-muted">- Safari: http://www.apple.com/legal/privacy/</p>
      <p className="mt-4 text-muted">- Chrome: https://support.google.com/accounts/answer/61416?hl=en</p>
      <p className="mt-4 text-muted">- Opera: http://www.opera.com/help/tutorials/security/cookies/</p>
      <p className="mt-4 text-muted">Log Data: Like all websites and mobile applications, this Website also makes use of log files which store automatic information collected during user visits. The different types of log data could be as follows:</p>
      <p className="mt-4 text-muted">- internet protocol (IP) address;- type of browser and device parameters used to connect to the Website;- name of the Internet Service Provider (ISP);- date and time of visit;- web page of origin of the user (referral) and exit;- possibly the number of clicks.</p>
      <p className="mt-4 text-muted">The aforementioned information is processed in an automated form and collected in an exclusively aggregated manner in order to verify the correct functioning of the site, and for security reasons. This information will be processed according to the legitimate interests of the Data Controller.</p>
      <p className="mt-4 text-muted">For security purposes (spam filters, firewalls, virus detection), the automatically recorded data may also possibly include Personal Data such as IP address, which could be used, in accordance with applicable laws, in order to block attempts at damage to the Website or damage to other users, or in the case of harmful activities or crime. Such data are never used for the identification or profiling of the user, but only for the protection of the Website and our users. Such information will be treated according to the legitimate interests of the Data Controller.</p>
      <p className="mt-4 text-muted">Article 8 - THIRD PARTIES:</p>
      <p className="mt-4 text-muted">We may utilize third party service providers ("Third Party Service Providers"), from time to time or all the time, to help us with our Website, and to help serve you.</p>
      <p className="mt-4 text-muted">We may use Third Party Service Providers to assist with information storage (such as cloud storage).</p>
      <p className="mt-4 text-muted">We may provide some of your Personal Data to Third Party Service Providers in order to help us track usage data, such as referral websites, dates and times of page requests, etc. We use this information to understand patterns of usage of, and to improve, the Website.</p>
      <p className="mt-4 text-muted">We may use Third Party Service Providers to host the Website. In this instance, the Third Party Service Provider will have access to your Personal Data.</p>
      <p className="mt-4 text-muted">We may allow third parties to advertise on the Website. These third parties may use cookies in connection with their advertisements (see the "Cookies" clause in this Privacy Policy).</p>
      <p className="mt-4 text-muted">Some of our Third Party Service Providers may be located outside of the United States and may not be subject to U.S. privacy laws. The countries or regions in which our Third Party Service Providers may be located include:</p>
      <p className="mt-4 text-muted">Venezuela.</p>
      <p className="mt-4 text-muted">EU.</p>
      <p className="mt-4 text-muted">We only share your Personal Data with a Third Party Service Provider if that provider agrees to our privacy standards as set out in this Privacy Policy.</p>
      <p className="mt-4 text-muted">Your Personal Data will not be sold or otherwise transferred to other third parties without your approval.</p>
      <p className="mt-4 text-muted">Notwithstanding the other provisions of this Privacy Policy, we may provide your Personal Data to a third party or to third parties in order to protect the rights, property or safety, of us, our customers or third parties, or as otherwise required by law.</p>
      <p className="mt-4 text-muted">We will not knowingly share your Personal Data with any third parties other than in accordance with this Privacy Policy.</p>
      <p className="mt-4 text-muted">If your Personal Data might be provided to a third party in a manner which is other than as explained in this Privacy Policy, you will be notified. you will also have the opportunity to request that we not share that information.</p>
      <p className="mt-4 text-muted">Article 9 - SOCIAL NETWORK PLUGINS:</p>
      <p className="mt-4 text-muted">This Website incorporates plugins and/or buttons for social networks, in order to allow easy sharing of content on your favorite social networks. These plugins are programmed so as not to set any cookies when accessing the page, to safeguard the privacy of users. Cookies may be set, however, if you make voluntary use of the plugin. Please note that if you browse while being logged into the social network then you have already consented to the use of cookies conveyed through this Website at the time that you registered with the particular social network.</p>
      <p className="mt-4 text-muted">The collection and use of information obtained by means of the plugin are governed by the respective privacy policies of the social networks, which can be found below:</p>
      <p className="mt-4 text-muted">Facebook: https://www.facebook.com/help/cookies</p>
      <p className="mt-4 text-muted">Twitter: https://help.twitter.com/en/rules-and-policies/twitter-cookies</p>
      <p className="mt-4 text-muted">Google+: http: //www.google.com/policies/technologies/cookies</p>
      <p className="mt-4 text-muted">Pinterest: https://about.pinterest.com/it/privacy-policy</p>
      <p className="mt-4 text-muted">AddThis: http://www.addthis.com/privacy/privacy-policy</p>
      <p className="mt-4 text-muted">Linkedin: https://www.linkedin.com/legal/cookie-policy</p>
      <p className="mt-4 text-muted">Article 10 - HOW PERSONAL DATA IS STORED:</p>
      <p className="mt-4 text-muted">We use secure physical and digital systems to store your Personal Data when appropriate. We ensure that your Personal Data is protected against unauthorized access, disclosure, or destructions.</p>
      <p className="mt-4 text-muted">Please note, however, that no system involving the transmission of information via the internet, or the electronic storage of data, is completely secure. However, we take the protection and storage of your Personal Data very seriously. We take all reasonable steps to protect your Personal Data.</p>
      <p className="mt-4 text-muted">Personal Data is stored throughout your relationship with us. We delete your Personal Data upon request for cancelation of your account or other general request for the deletion of data.</p>
      <p className="mt-4 text-muted">In the event of a breach of your Personal Data, you will be notified in a reasonable time frame, but in no event later than two weeks, and we will follow all applicable laws regarding such breach.</p>
      <p className="mt-4 text-muted">Article 11 - PURPOSES OF PROCESSING OF PERSONAL DATA:</p>
      <p className="mt-4 text-muted">We primarily use your Personal Data to help us provide a better experience for you on our Website and to provide you the services and/or information you may have requested, such as use of our Website.</p>
      <p className="mt-4 text-muted">Information that does not identify you personally, but that may assist in providing us broad overviews of our customer base, will be used for market research or marketing efforts. Such information may include, but is not limited to, interests based on your cookies.</p>
      <p className="mt-4 text-muted">Personal Data that may be considering identifying may be used for the following:</p>
      <p className="mt-4 text-muted">a) Improving your personal user experience</p>
      <p className="mt-4 text-muted">b) Communicating with you about your user account with us</p>
      <p className="mt-4 text-muted">c) Marketing and advertising to you, including via email</p>
      <p className="mt-4 text-muted">d) Fulfilling your purchases</p>
      <p className="mt-4 text-muted">e) Providing customer service to you</p>
      <p className="mt-4 text-muted">f) Advising you about updates to the Website or related Items</p>
      <p className="mt-4 text-muted">Article 12 - DISCLOSURE OF PERSONAL DATA:</p>
      <p className="mt-4 text-muted">Although our policy is to maintain the privacy of your Personal Data as described herein, we may disclose your Personal Data if we believe that it is reasonable to do so in certain cases, in our sole and exclusive discretion. Such cases may include, but are not limited to:</p>
      <p className="mt-4 text-muted">a) To satisfy any local, state, or Federal laws or regulations</p>
      <p className="mt-4 text-muted">b) To respond to requests, such discovery, criminal, civil, or administrative process, subpoenas, court orders, or writs from law enforcement or other governmental or legal bodies</p>
      <p className="mt-4 text-muted">c) To bring legal action against a user who has violated the law or violated the terms of use of our Website</p>
      <p className="mt-4 text-muted">d) As may be necessary for the operation of our Website</p>
      <p className="mt-4 text-muted">e) To generally cooperate with any lawful investigation about our users</p>
      <p className="mt-4 text-muted">f) If we suspect any fraudulent activity on our Website or if we have noticed any activity which may violate our terms or other applicable rules</p>
      <p className="mt-4 text-muted">Article 13 - PUBLIC INFORMATION:</p>
      <p className="mt-4 text-muted">We may allow users to post their own content or information publicly on our Website. Such content or information may include, but is not limited to, photographs, status updates, blogs, articles, or other personal snippets. Please be aware that any such information or content that you may post should be considered entirely public and that we do not purport to maintain the privacy of such public information.</p>
      <p className="mt-4 text-muted">Article 14 - OPTING OUT OF TRANSMITTALS FROM US:</p>
      <p className="mt-4 text-muted">From time to time, we may send you informational or marketing communications related to our Website such as announcements or other information. If you wish to opt-out of such communications, you may contact the following email: info@tuataras.local. You may also click the opt-out link which will be provided at the bottom of any and all such communications.</p>
      <p className="mt-4 text-muted">Please be advised that even though you may opt-out of such communications, you may still receive information from us that is specifically about your use of our Website or about your account with us.</p>
      <p className="mt-4 text-muted">By providing any Personal Data to us, or by using our Website in any manner, you have created a commercial relationship with us. As such, you agree that any email sent from us or third-party affiliates, even unsolicited email, shall specifically not be considered SPAM, as that term is legally defined.</p>
      <p className="mt-4 text-muted">Article 15 - MODIFYING, DELETING, AND ACCESSING YOUR INFORMATION:</p>
      <p className="mt-4 text-muted">If you wish to modify or delete any information we may have about you, or you wish to simply access any information we have about you, you may reach out to us at the following email address: info@tuataras.local.</p>
      <p className="mt-4 text-muted">Article 16 - ACCEPTANCE OF RISK:</p>
      <p className="mt-4 text-muted">By continuing to our Website in any manner, use the Product, you manifest your continuing asset to this Privacy Policy. You further acknowledge, agree and accept that no transmission of information or data via the internet is not always completely secure, no matter what steps are taken. You acknowledge, agree and accept that we do not guarantee or warrant the security of any information that you provide to us, and that you transmit such information at your own risk.</p>
      <p className="mt-4 text-muted">Article 17 - YOUR RIGHTS:</p>
      <p className="mt-4 text-muted">You have many rights in relation to your Personal Data. Specifically, your rights are as follows:</p>
      <p className="mt-4 text-muted">- the right to be informed about the processing of your Personal Dat</p>
      <p className="mt-4 text-muted">- the right to have access to your Personal Data</p>
      <p className="mt-4 text-muted">- the right to update and/or correct your Personal Data</p>
      <p className="mt-4 text-muted">- the right to portability of your Personal Data</p>
      <p className="mt-4 text-muted">- the right to oppose or limit the processing of your Personal Data</p>
      <p className="mt-4 text-muted">- the right to request that we stop processing and delete your Personal Data</p>
      <p className="mt-4 text-muted">- the right to block any Personal Data processing in violation of any applicable law</p>
      <p className="mt-4 text-muted">- the right to launch a complaint with the Federal Trade Commission (FTC) in the United States or applicable data protection authority in another jurisdiction</p>
      <p className="mt-4 text-muted">Such rights can all be exercised by contacting us at the relevant contact information listed in this Privacy Policy.</p>
      <p className="mt-4 text-muted">Article 18 - CONTACT INFORMATION:</p>
      <p className="mt-4 text-muted">If you have any questions about this Privacy Policy or the way we collect information from you, or if you would like to launch a complaint about anything related to this Privacy Policy, you may contact us at the following email address: legal@tuataras.local.</p>
    </PageShell>
  );
}
