import type { Metadata } from "next";
import { PageShell } from "@/components/PageShell";

export const metadata: Metadata = {
  title: "Política de Privacidad | Tuataras",
  description: "Política de privacidad y protección de datos de Tuataras.",
  robots: { index: false, follow: false },
};

export default function Page() {
  return (
    <PageShell lang="es" title="Política de privacidad">
      <p className="mt-4 text-muted">POLÍTICA DE PRIVACIDAD DEL SITIO WEB</p>
      <p className="mt-4 text-muted">http://tuataras.local</p>
      <p className="mt-4 text-muted">POLÍTICA DE PRIVACIDAD Y PROTECCIÓN DE DATOS</p>
      <p className="mt-4 text-muted">Respetando lo establecido en la legislación vigente, Tuataras (en adelante, también Sitio Web) se compromete a adoptar las medidas técnicas y organizativas necesarias, según el nivel de seguridad adecuado al riesgo de los datos recogidos.</p>
      <p className="mt-4 text-muted">Leyes que incorpora esta política de privacidad</p>
      <p className="mt-4 text-muted">Esta política de privacidad está adaptada a la normativa española y europea vigente en materia de protección de datos personales en internet. En concreto, la misma respeta las siguientes normas:</p>
      <p className="mt-4 text-muted">La Ley Orgánica 3/2018, de 5 de diciembre, de Protección de Datos Personales y garantía de los derechos digitales.</p>
      <p className="mt-4 text-muted">El Reglamento (UE) 2016/679 del Parlamento Europeo y del Consejo, de 27 de abril de 2016, relativo a la protección de las personas físicas en lo que respecta al tratamiento de datos personales y a la libre circulación de estos datos (RGPD).</p>
      <p className="mt-4 text-muted">El Real Decreto 1720/2007, de 21 de diciembre, por el que se aprueba el Reglamento de desarrollo de la Ley Orgánica 15/1999, de 13 de diciembre, de Protección de Datos de Carácter Personal (RDLOPD).</p>
      <p className="mt-4 text-muted">La Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y de Comercio Electrónico (LSSI-CE).</p>
      <p className="mt-4 text-muted">Identidad del responsable del tratamiento de los datos personales</p>
      <p className="mt-4 text-muted">Los responsables del tratamiento de los datos personales recogidos en Tuataras son:</p>
      <p className="mt-4 text-muted">Tuataras.LLC</p>
      <p className="mt-4 text-muted">Los anteriores (en adelante, también Responsable del tratamiento) determinan conjuntamente los objetivos y los medios del tratamiento, siendo considerados corresponsables del tratamiento. Así, determinan de modo transparente y de mutuo acuerdo sus responsabilidades respectivas en el cumplimiento de las obligaciones impuestas por el RGPD. Respetando lo previsto en el artículo 26 del RGPD, los aspectos esenciales de dicho acuerdo estarán a disposición del Usuario en el siguiente enlace: http://tuataras.local</p>
      <p className="mt-4 text-muted">Sus datos de contacto son los siguientes:</p>
      <p className="mt-4 text-muted">Dirección: 1480 NW North River Drive, Miami, FL 33125</p>
      <p className="mt-4 text-muted">Teléfono de contacto: SKYPE Tuataras</p>
      <p className="mt-4 text-muted">Email de contacto: info@tuataras.local</p>
      <p className="mt-4 text-muted">Delegado de Protección de Datos (DPD)</p>
      <p className="mt-4 text-muted">El Delegado de Protección de Datos (DPD, o DPO por sus siglas en inglés) es el encargado de velar por el cumplimiento de la normativa de protección de datos a la cual se encuentra sujeta Tuataras. El Usuario puede contactar con el DPD designado por el Responsable del tratamiento utilizando los siguientes datos de contacto: info@tuataras.local.</p>
      <p className="mt-4 text-muted">Registro de Datos de Carácter Personal</p>
      <p className="mt-4 text-muted">Los datos personales recabados por Tuataras, mediante los formularios extendidos en sus páginas, serán introducidos en un fichero automatizado bajo la responsabilidad del Responsable del tratamiento, y debidamente declarado e inscrito en el Registro General de la Agencia de Protección de Datos que se puede consultar en el sitio web de la Agencia Española de Protección de Datos (http://www.agpd.es), con la finalidad de poder facilitar, agilizar y cumplir los compromisos establecidos entre Tuataras y el Usuario o el mantenimiento de la relación que se establezca en los formularios que este rellene, o para atender una solicitud o consulta del mismo.</p>
      <p className="mt-4 text-muted">Principios aplicables al tratamiento de los datos personales</p>
      <p className="mt-4 text-muted">El tratamiento de los datos personales del Usuario se someterá a los siguientes principios recogidos en el artículo 5 del RGPD y en el artículo 4 y siguientes de la Ley Orgánica 3/2018, de 5 de diciembre, de Protección de Datos Personales y garantía de los derechos digitales:</p>
      <p className="mt-4 text-muted">Principio de licitud, lealtad y transparencia: se requerirá en todo momento el consentimiento del Usuario previa información completamente transparente de los fines para los cuales se recogen los datos personales.</p>
      <p className="mt-4 text-muted">Principio de limitación de la finalidad: los datos personales serán recogidos con fines determinados, explícitos y legítimos.</p>
      <p className="mt-4 text-muted">Principio de minimización de datos: los datos personales recogidos serán únicamente los estrictamente necesarios en relación con los fines para los que son tratados.</p>
      <p className="mt-4 text-muted">Principio de exactitud: los datos personales deben ser exactos y estar siempre actualizados.</p>
      <p className="mt-4 text-muted">Principio de limitación del plazo de conservación: los datos personales solo serán mantenidos de forma que se permita la identificación del Usuario durante el tiempo necesario para los fines de su tratamiento.</p>
      <p className="mt-4 text-muted">Principio de integridad y confidencialidad: los datos personales serán tratados de manera que se garantice su seguridad y confidencialidad.</p>
      <p className="mt-4 text-muted">Principio de responsabilidad proactiva: el Responsable del tratamiento será responsable de asegurar que los principios anteriores se cumplen.</p>
      <p className="mt-4 text-muted">Categorías de datos personales</p>
      <p className="mt-4 text-muted">Las categorías de datos que se tratan en Tuataras son únicamente datos identificativos. En ningún caso, se tratan categorías especiales de datos personales en el sentido del artículo 9 del RGPD.</p>
      <p className="mt-4 text-muted">Base legal para el tratamiento de los datos personales</p>
      <p className="mt-4 text-muted">La base legal para el tratamiento de los datos personales es el consentimiento. Tuataras se compromete a recabar el consentimiento expreso y verificable del Usuario para el tratamiento de sus datos personales para uno o varios fines específicos.</p>
      <p className="mt-4 text-muted">El Usuario tendrá derecho a retirar su consentimiento en cualquier momento. Será tan fácil retirar el consentimiento como darlo. Como regla general, la retirada del consentimiento no condicionará el uso del Sitio Web.</p>
      <p className="mt-4 text-muted">En las ocasiones en las que el Usuario deba o pueda facilitar sus datos a través de formularios para realizar consultas, solicitar información o por motivos relacionados con el contenido del Sitio Web, se le informará en caso de que la cumplimentación de alguno de ellos sea obligatoria debido a que los mismos sean imprescindibles para el correcto desarrollo de la operación realizada.</p>
      <p className="mt-4 text-muted">Períodos de retención de los datos personales</p>
      <p className="mt-4 text-muted">Los datos personales solo serán retenidos durante el tiempo mínimo necesario para los fines de su tratamiento y, en todo caso, únicamente durante el siguiente plazo: Indefinido, o hasta que el Usuario solicite su supresión.</p>
      <p className="mt-4 text-muted">En el momento en que se obtengan los datos personales, se informará al Usuario acerca del plazo durante el cual se conservarán los datos personales o, cuando eso no sea posible, los criterios utilizados para determinar este plazo.</p>
      <p className="mt-4 text-muted">Destinatarios de los datos personales</p>
      <p className="mt-4 text-muted">Los datos personales del Usuario no serán compartidos con terceros.</p>
      <p className="mt-4 text-muted">En cualquier caso, en el momento en que se obtengan los datos personales, se informará al Usuario acerca de los destinatarios o las categorías de destinatarios de los datos personales.</p>
      <p className="mt-4 text-muted">Datos personales de menores de edad</p>
      <p className="mt-4 text-muted">Respetando lo establecido en los artículos 8 del RGPD y 7 de la Ley Orgánica 3/2018, de 5 de diciembre, de Protección de Datos Personales y garantía de los derechos digitales, solo los mayores de 14 años podrán otorgar su consentimiento para el tratamiento de sus datos personales de forma lícita por Tuataras. Si se trata de un menor de 14 años, será necesario el consentimiento de los padres o tutores para el tratamiento, y este solo se considerará lícito en la medida en la que los mismos lo hayan autorizado.</p>
      <p className="mt-4 text-muted">Secreto y seguridad de los datos personales</p>
      <p className="mt-4 text-muted">Tuataras se compromete a adoptar las medidas técnicas y organizativas necesarias, según el nivel de seguridad adecuado al riesgo de los datos recogidos, de forma que se garantice la seguridad de los datos de carácter personal y se evite la destrucción, pérdida o alteración accidental o ilícita de datos personales transmitidos, conservados o tratados de otra forma, o la comunicación o acceso no autorizados a dichos datos.</p>
      <p className="mt-4 text-muted">El Sitio Web cuenta con un certificado SSL (Secure Socket Layer), que asegura que los datos personales se transmiten de forma segura y confidencial, al ser la transmisión de los datos entre el servidor y el Usuario, y en retroalimentación, totalmente cifrada o encriptada.</p>
      <p className="mt-4 text-muted">Sin embargo, debido a que Tuataras no puede garantizar la inexpugabilidad de internet ni la ausencia total de hackers u otros que accedan de modo fraudulento a los datos personales, el Responsable del tratamiento se compromete a comunicar al Usuario sin dilación indebida cuando ocurra una violación de la seguridad de los datos personales que sea probable que entrañe un alto riesgo para los derechos y libertades de las personas físicas. Siguiendo lo establecido en el artículo 4 del RGPD, se entiende por violación de la seguridad de los datos personales toda violación de la seguridad que ocasione la destrucción, pérdida o alteración accidental o ilícita de datos personales transmitidos, conservados o tratados de otra forma, o la comunicación o acceso no autorizados a dichos datos.</p>
      <p className="mt-4 text-muted">Los datos personales serán tratados como confidenciales por el Responsable del tratamiento, quien se compromete a informar de y a garantizar por medio de una obligación legal o contractual que dicha confidencialidad sea respetada por sus empleados, asociados, y toda persona a la cual le haga accesible la información.</p>
      <p className="mt-4 text-muted">Derechos derivados del tratamiento de los datos personales</p>
      <p className="mt-4 text-muted">El Usuario tiene sobre Tuataras y podrá, por tanto, ejercer frente al Responsable del tratamiento los siguientes derechos reconocidos en el RGPD y en la Ley Orgánica 3/2018, de 5 de diciembre, de Protección de Datos Personales y garantía de los derechos digitales:</p>
      <p className="mt-4 text-muted">Derecho de acceso: Es el derecho del Usuario a obtener confirmación de si Tuataras está tratando o no sus datos personales y, en caso afirmativo, obtener información sobre sus datos concretos de carácter personal y del tratamiento que Tuataras haya realizado o realice, así como, entre otra, de la información disponible sobre el origen de dichos datos y los destinatarios de las comunicaciones realizadas o previstas de los mismos.</p>
      <p className="mt-4 text-muted">Derecho de rectificación: Es el derecho del Usuario a que se modifiquen sus datos personales que resulten ser inexactos o, teniendo en cuenta los fines del tratamiento, incompletos.</p>
      <p className="mt-4 text-muted">Derecho de supresión ("el derecho al olvido"): Es el derecho del Usuario, siempre que la legislación vigente no establezca lo contrario, a obtener la supresión de sus datos personales cuando estos ya no sean necesarios para los fines para los cuales fueron recogidos o tratados; el Usuario haya retirado su consentimiento al tratamiento y este no cuente con otra base legal; el Usuario se oponga al tratamiento y no exista otro motivo legítimo para continuar con el mismo; los datos personales hayan sido tratados ilícitamentemente; los datos personales deban suprimirse en cumplimiento de una obligación legal; o los datos personales hayan sido obtenidos producto de una oferta directa de servicios de la sociedad de la información a un menor de 14 años. Además de suprimir los datos, el Responsable del tratamiento, teniendo en cuenta la tecnología disponible y el coste de su aplicación, deberá adoptar medidas razonables para informar a los responsables que estén tratando los datos personales de la solicitud del interesado de supresión de cualquier enlace a esos datos personales.</p>
      <p className="mt-4 text-muted">Derecho a la limitación del tratamiento: Es el derecho del Usuario a limitar el tratamiento de sus datos personales. El Usuario tiene derecho a obtener la limitación del tratamiento cuando impugne la exactitud de sus datos personales; el tratamiento sea ilícito; el Responsable del tratamiento ya no necesite los datos personales, pero el Usuario lo necesite para hacer reclamaciones; y cuando el Usuario se haya opuesto al tratamiento.</p>
      <p className="mt-4 text-muted">Derecho a la potabilidad de los datos: En caso de que el tratamiento se efectúe por medios automatizados, el Usuario tendrá derecho a recibir del Responsable del tratamiento sus datos personales en un formato estructurado, de uso común y lectura mecánica, y a transmitirlos a otro responsable del tratamiento. Siempre que sea técnicamente posible, el Responsable del tratamiento transmitirá directamente los datos a ese otro responsable.</p>
      <p className="mt-4 text-muted">Derecho de oposición: Es el derecho del Usuario a que no se lleve a cabo el tratamiento de sus datos de carácter personal o se cese el tratamiento de los mismos por parte de Tuataras.</p>
      <p className="mt-4 text-muted">Derecho a no ser a no ser objeto de una decisión basada únicamente en el tratamiento automatizado, incluida la elaboración de perfiles: Es el derecho del Usuario a no ser objeto de una decisión individualizada basada únicamente en el tratamiento automatizado de sus datos personales, incluida la elaboración de perfiles, existente salvo que la legislación vigente establezca lo contrario.</p>
      <p className="mt-4 text-muted">Así pues, el Usuario podrá ejercitar sus derechos mediante comunicación escrita dirigida al Responsable del tratamiento con la referencia "RGPD- http://tuataras.local especificando:</p>
      <p className="mt-4 text-muted">Nombre, apellidos del Usuario y copia del DNI. En los casos en que se admita la representación, será también necesaria la identificación por el mismo medio de la persona que representa al Usuario, así como el documento acreditativo de la representación. La fotocopia del DNI podrá ser sustituida, por cualquier otro medio válido en derecho que acredite la identidad.</p>
      <p className="mt-4 text-muted">Petición con los motivos específicos de la solicitud o información a la que se quiere acceder.</p>
      <p className="mt-4 text-muted">Domicilio a efecto de notificaciones.</p>
      <p className="mt-4 text-muted">Fecha y firma del solicitante.</p>
      <p className="mt-4 text-muted">Todo documento que acredite la petición que formula.</p>
      <p className="mt-4 text-muted">Esta solicitud y todo otro documento adjunto podrá enviarse a la siguiente dirección y/o correo electrónico:</p>
      <p className="mt-4 text-muted">Dirección postal:</p>
      <p className="mt-4 text-muted">Correo electrónico: info@tuataras.local</p>
      <p className="mt-4 text-muted">Reclamaciones ante la autoridad de control</p>
      <p className="mt-4 text-muted">En caso de que el Usuario considere que existe un problema o infracción de la normativa vigente en la forma en la que se están tratando sus datos personales, tendrá derecho a la tutela judicial efectiva y a presentar una reclamación ante una autoridad de control, en particular, en el Estado en el que tenga su residencia habitual, lugar de trabajo o lugar de la supuesta infracción. En el caso de España, la autoridad de control es la Agencia Española de Protección de Datos (http://www.agpd.es).</p>
      <p className="mt-4 text-muted">POLÍTICA DE COOKIES</p>
      <p className="mt-4 text-muted">El acceso a este Sitio Web puede implicar la utilización de cookies. Las cookies son pequeñas cantidades de información que se almacenan en el navegador utilizado por cada Usuario -en los distintos dispositivos que pueda utilizar para navegar- para que el servidor recuerde cierta información que posteriormente y únicamente el servidor que la implemento leerá. Las cookies facilitan la navegación, la hacen más amigable, y no dañan el dispositivo de navegación.</p>
      <p className="mt-4 text-muted">La información recabada a través de las cookies puede incluir la fecha y hora de visitas al Sitio Web, las páginas visionadas, el tiempo que ha estado en el Sitio Web y los sitios visitados justo antes y después del mismo. Sin embargo, ninguna cookie permite que esta misma pueda contactarse con el número de teléfono del Usuario o con cualquier otro medio de contacto personal. Ninguna cookie puede extraer información del disco duro del Usuario o robar información personal. La única manera de que la información privada del Usuario forme parte del archivo Cookie es que el usuario dé personalmente esa información al servidor.</p>
      <p className="mt-4 text-muted">Las cookies que permiten identificar a una persona se consideran datos personales. Por tanto, a las mismas les será de aplicación la Política de Privacidad anteriormente descrita. En este sentido, para la utilización de las mismas será necesario el consentimiento del Usuario. Este consentimiento será comunicado, en base a una elección auténtica, ofrecido mediante una decisión afirmativa y positiva, antes del tratamiento inicial, removible y documentado.</p>
      <p className="mt-4 text-muted">Cookies propias</p>
      <p className="mt-4 text-muted">Son aquellas cookies que son enviadas al ordenador o dispositivo del Usuario y gestionadas exclusivamente por Tuataras para el mejor funcionamiento del Sitio Web. La información que se recaba se emplea para mejorar la calidad del Sitio Web y su Contenido y su experiencia como Usuario. Estas cookies permiten reconocer al Usuario como visitante recurrente del Sitio Web y adaptar el contenido para ofrecerle contenidos que se ajusten a sus preferencias.</p>
      <p className="mt-4 text-muted">Cookies de terceros</p>
      <p className="mt-4 text-muted">Son cookies utilizadas y gestionadas por entidades externas que proporcionan a Tuataras servicios solicitados por este mismo para mejorar el Sitio Web y la experiencia del usuario al navegar en el Sitio Web. Los principales objetivos para los que se utilizan cookies de terceros son la obtención de estadísticas de accesos y analizar la información de la navegación, es decir, cómo interactúa el Usuario con el Sitio Web.</p>
      <p className="mt-4 text-muted">La información que se obtiene se refiere, por ejemplo, al número de páginas visitadas, el idioma, el lugar a la que la dirección IP desde el que accede el Usuario, el número de Usuarios que acceden, la frecuencia y reincidencia de las visitas, el tiempo de visita, el navegador que usan, el operador o tipo de dipositivo desde el que se realiza la visita. Esta información se utiliza para mejorar el Sitio Web, y detectar nuevas necesidades para ofrecer a los Usuarios un Contenido y/o servicio de óptima calidad. En todo caso, la información se recopila de forma anónima y se elaboran informes de tendencias del Sitio Web sin identificar a usuarios individuales.</p>
      <p className="mt-4 text-muted">Puede obtener más información sobre las cookies, la información sobre la privacidad, o consultar la descripción del tipo de cookies que se utiliza, sus principales características, periodo de expiración, etc. en el siguiente(s) enlace(s):</p>
      <p className="mt-4 text-muted">Google Analytics</p>
      <p className="mt-4 text-muted">https://analytics.google.com/analytics/web/</p>
      <p className="mt-4 text-muted">La(s) entidad(es) encargada(s) del suministro de cookies podrá(n) ceder esta información a terceros, siempre y cuando lo exija la ley o sea un tercero el que procese esta información para dichas entidades.</p>
      <p className="mt-4 text-muted">Cookies de redes sociales</p>
      <p className="mt-4 text-muted">Tuataras incorpora plugins de redes sociales, que permiten acceder a las mismas a partir del Sitio Web. Por esta razón, las cookies de redes sociales pueden almacenarse en el navegador del Usuario. Los titulares de dichas redes sociales disponen de sus propias políticas de protección de datos y de cookies, siendo ellos mismos, en cada caso, responsables de sus propios ficheros y de sus propias prácticas de privacidad. El Usuario debe referirse a las mismas para informarse acerca de dichas cookies y, en su caso, del tratamiento de sus datos personales. Únicamente a título informativo se indican a continuación los enlaces en los que se pueden consultar dichas políticas de privacidad y/o de cookies:</p>
      <p className="mt-4 text-muted">Facebook: https://www.facebook.com/policies/cookies/</p>
      <p className="mt-4 text-muted">Twitter: https://twitter.com/es/privacy</p>
      <p className="mt-4 text-muted">Instagram: https://help.instagram.eom/T896641480634370?ref=ig</p>
      <p className="mt-4 text-muted">Youtube: https://policies.google.com/privacy?hl=es-419&amp;gl=mx</p>
      <p className="mt-4 text-muted">Google+: https://policies.google.com/technologies/cookies?hl=es</p>
      <p className="mt-4 text-muted">Pinterest: https://policy.pinterest.com/es/privacy-policy</p>
      <p className="mt-4 text-muted">Linkedln: https://www.linkedin.com/legal/cookie-policy?trk=hp-cookies</p>
      <p className="mt-4 text-muted">Deshabilitar, rechazar y eliminar cookies</p>
      <p className="mt-4 text-muted">El Usuario puede deshabilitar, rechazar y eliminar las cookies -total o parcialmente- instaladas en su dispositivo mediante la configuración de su navegador (entre los que se encuentran, por ejemplo, Chrome, Firefox, Safari, Explorer). En este sentido, los procedimientos para rechazar y eliminar las cookies pueden diferir de un navegador de Internet a otro. En consecuencia, el Usuario debe acudir a las instrucciones facilitadas por el propio navegador de Internet que esté utilizando. En el supuesto de que rechace el uso de cookies -total o parcialmente- podrá seguir usando el Sitio Web, si bien podrá tener limitada la utilización de algunas de las prestaciones del mismo.</p>
      <p className="mt-4 text-muted">&nbsp;</p>
      <p className="mt-4 text-muted">ACEPTACIÓN Y CAMBIOS EN ESTA POLÍTICA DE PRIVACIDAD</p>
      <p className="mt-4 text-muted">Es necesario que el Usuario haya leído y esté conforme con las condiciones sobre la protección de datos de carácter personal contenidas en esta Política de Privacidad y de Cookies, así como que acepte el tratamiento de sus datos personales para que el Responsable del tratamiento pueda proceder al mismo en la forma, durante los plazos y para las finalidades indicadas. El uso del Sitio Web implicará la aceptación de la Política de Privacidad y de Cookies del mismo.</p>
      <p className="mt-4 text-muted">Tuataras se reserva el derecho a modificar su Política de Privacidad y de Cookies, de acuerdo a su propio criterio, o motivado por un cambio legislativo, jurisprudencial o doctrinal de la Agencia Española de Protección de Datos. Los cambios o actualizaciones de esta Política de Privacidad y de Cookies no serán notificados de forma explícita al Usuario. Se recomienda al Usuario consultar esta página de forma periódica para estar al tanto de los últimos cambios o actualizaciones.</p>
      <p className="mt-4 text-muted">Esta Política de Privacidad y de Cookies fue actualizada el día 9 de julio 2019 para adaptarse al Reglamento (UE) 2016/679 del Parlamento Europeo y del Consejo, de 27 de abril de 2016, relativo a la protección de las personas físicas en lo que respecta al tratamiento de datos personales y a la libre circulación de estos datos (RGPD) y a la Ley Orgánica 3/2018, de 5 de diciembre, de Protección de Datos Personales y garantía de los derechos digitales.</p>
    </PageShell>
  );
}
